### ISSUE TITLE
write language independent tests

### ISSUE THREAD

**Issue by reece** [ga4gh/vmc#18]
The goal of this issue to make a set of tests that can be used to validate implementations of the VMC specification. After an [initial set of ideas](https://docs.google.com/document/d/12TU0ftgytfi0cJh-MX4sexw32YmYZ8b7B1s4vGhpeuY/edit?ts=5a281ee4), this issue is reformulated to provide the following tests:

## Function tests
* truncated_digest: Provide digests for short strings (e.g., '', 'vmc', 'VMC') 
* sequence id lookup: Provide tests for external accession → VMC digest (e.g., NC_000019.10 → VMC:GS_IIB53T8CNeJJdUqzn9V_JnRtQadwWCbl)

## Object generation, serialization, computed ids
Provide serialization tests (and digests for identifiable objects) of generating primitive objects generated from yaml/json data 
* Interval
* Location
* Allele
* Haplotype
* Genotype

## Conversion tests
* Tests of VCF (ref, alt) to VMC
* HGVS (strings) to VMC

**Comment by reece** [comment]
Progress! Test definitions are in a yaml file and tests can be written against these. Example for `truncated_digest` function:

```
truncated_digest:
  description: ...
  tests:
    -
      # >>> _truncated_digest(b"", digest_size=24)
      # b'z4PhNX7vuL3xVChQ1m2AB9Yg5AULVxXc'
      in:
        blob: ""
        digest_size: 24
      out:
        z4PhNX7vuL3xVChQ1m2AB9Yg5AULVxXc
    -
      # >>> _truncated_digest(b"", digest_size=18)
      # b'z4PhNX7vuL3xVChQ1m2AB9Yg'
      in:
        blob: ""
        digest_size: 18
      out:
        z4PhNX7vuL3xVChQ1m2AB9Yg
    -
      # >>> _truncated_digest(b"", digest_size=9)
      # b'z4PhNX7vuL3x'
      in:
        blob: ""
        digest_size: 9
      out:
        z4PhNX7vuL3x
        
    -
      # >>> _truncated_digest(b"ACGT", digest_size=24)
      # b'aKF498dAxcJAqme6QYQ7EZ07-fiw8Kw2'
      in:
        blob: ACGT
        digest_size: 24
      out:
        aKF498dAxcJAqme6QYQ7EZ07-fiw8Kw2
```

In python, the test looks like this:

```
import os

import pytest
import yaml

from vmc.digest import _truncated_digest

validation_fn = os.path.join(os.path.dirname(__file__), "..", "vmc-spec", "tests", "validation.yaml")

validation_tests = yaml.load(open(validation_fn))

@pytest.mark.parametrize("td_test", validation_tests["truncated_digest"]["tests"])
def test_truncated_digest(td_test):
    def td_wrapper(blob, digest_size):
        return _truncated_digest(blob.encode("ascii"), digest_size).decode("ascii")
    assert td_test["out"] == td_wrapper(**td_test["in"])
```
